// <auto-generated />
using System;
using DEPLOY.EntityFramework.v1.Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DEPLOY.EntityFramework.v1.Migrations.EF
{
    [DbContext(typeof(DeployDbContext))]
    partial class DeployDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContratoPessoa", b =>
                {
                    b.Property<Guid>("ContratosId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InteressadosId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ContratosId", "InteressadosId");

                    b.HasIndex("InteressadosId");

                    b.ToTable("ContratoPessoa");
                });

            modelBuilder.Entity("DEPLOY.EntityFramework.v1.Domain.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ContratoId");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("Ativo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("DataFim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("DataInicio");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("Numero");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Contratos", (string)null);
                });

            modelBuilder.Entity("DEPLOY.EntityFramework.v1.Domain.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PessoaId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Endereco", "Documento" }, "IX_Names_Descending")
                        .IsDescending();

                    b.ToTable("Pessoas", (string)null);
                });

            modelBuilder.Entity("ContratoPessoa", b =>
                {
                    b.HasOne("DEPLOY.EntityFramework.v1.Domain.Contrato", null)
                        .WithMany()
                        .HasForeignKey("ContratosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DEPLOY.EntityFramework.v1.Domain.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("InteressadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
